### ISSUE TITLE
使用本地文件配置bot以及发布教学视频

### ISSUE THREAD

**Issue by Enderman-TPing** [ForteScarlet/simpler-robot#503]
### 建议描述

1.希望在B站上发布v3的教程
2.希望将.bot bot配置文件放入cache文件夹中以便随时配置

**Comment by ForteScarlet** [comment]
1. 视频教程会在一个稳定版发布之后（例如 `v3.0.0`）再开始考虑，在稳定之前暂时没有计划，时间也不太够。但是我们很欢迎社区自由发挥的发布相关教学视频（疯狂暗示）
2. `cache` 文件夹是由 mirai 创建的，与simbot无关。
   如果指的是希望通过外部文件读取配置文件而不是资源路径，在SpringBoot环境下可以通过 [`simbot.bot-configuration-resources`](https://simbot.forte.love/docs/quick-start/spring-boot-starter#%E9%85%8D%E7%BD%AE) 来指定文件目录（`file:`）而不是资源路径（`classpath:`）。普通的boot模块也可以通过修改配置来调整加载bot配置文件的方式和路径。
```yaml
simbot:
  bot-configuration-resources:
    - 'file:simbot-bots/*.json'
```
