### ISSUE TITLE
配置bot-configuration-resources失效

### ISSUE THREAD

**Issue by lanlanwa** [ForteScarlet/simpler-robot#550]
### 版本号

simbot-starter-3.0.0-M5  simbot-mirai-core-3.0.0.0-beta.6

### 问题描述

更新后找不到机器人，检查后发现打印日志
Can not resolve resource path 「simbot-bots/*.bot*」: class path resource [simbot-bots/] cannot be resolved to URL because it does not exist, just use empty resources.

配置如下：
```yaml
simbot:
  # 是否在bot注册完成后自动启动他们。
  # 默认为 true
  auto-start-bots: true

  # 自定义配置bot资源文件的扫描路径。
  # 默认为 'classpath:simbot-bots/*.bot*'
  bot-configuration-resources:
    - 'classpath:*.bot*'
```

### 复现方式

直接Debug Springboot项目
